---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace | quote }}
  labels:
    {{- include "red-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - {{ include "red-chart.fqdn" . | quote }}
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - {{ include "red-chart.fqdn" . | quote }}
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ include "red-chart.fullname" . }}-cert-tls
