{{- if eq .Values.routingMode "gatewayapi" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace | quote }}
  annotations:
    {{- if not .Values.certificate.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certificate.issuer }}
    {{- end }}
    {{- range $key, $val := .Values.gateway.annotations }}
    {{- if or $.Values.certificate.enabled (ne $key "cert-manager.io/cluster-issuer") }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "red-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      hostname: {{ include "red-chart.fqdn" . }}
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: {{ include "red-chart.fqdn" . }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ include "red-chart.fullname" . }}-cert-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
{{- end }}
